# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "Beer & Code"
  description: "O melhor evento de cerveja e código da Região Norte!"
  date: "26 de Março de 2016"
  price: "Vagas limitadas!"
  address: "Avenida Lauro Sodré 2300, Olaria, Porto Velho, RO"
  venue: "Condomínio Reserva do Bosque"
  city: "Porto Velho - RO"

# Site info
site:
  url: "http://www.beerandcode.ro"
  favicon: "#"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "http://i.imgur.com/DyuPfIT.jpg"
    facebook: "http://i.imgur.com/ZXtTAga.png"

subscribe_text: "Inscreva-se!"
subscribe_url: "http://www.eventick.com.br/beer-and-code-ro-2016"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: true
  sponsors: false
  partners: true
  contact: false

# The entire schedule
schedule:
  -
    name: "Abertura do Evento"
    time: "16h00"
  -
    name: "Homenagem e dedicatória ao idealizador do evento"
    time: "16h15"
  -
    name: "Patrocinador"
    time: "16h30"
  -
    name: "Bruno Pinheiro"
    photo: "http://i.imgur.com/IQyOSp3.jpg"
    bio: "Gerente de projetos na Superintendência Estadual de Assuntos Estratégicos do Governo de Rondônia, com 10 anos de experiência em infra-estrutura de redes, vê na informática a solução para a maioria dos problemas no Estado e no mundo."
    company: "Superintendência Estadual de Assuntos Estratégicos de Rondônia (SEAE-RO)"
    presentation:
      title: "Open Flow"
      time: "17h00"
  -
    name: "Lucas Bernieri"
    photo: "http://i.imgur.com/flD8YkH.jpg"
    bio: "Tecnólogo em Sistemas para Internet, Desenvolvedor Front-end e Back-end, atua na área há 2 anos."
    company: "Netpix Agência Web"
    presentation:
      title: "ReactJS"
      time: "18h00"
  -
    name: "Gustavo Richetti"
    photo: "http://i.imgur.com/P0tHXmm.jpg"
    bio: "Analista de sistemas formado em informática pela universidade federal de Rondônia, atualmente trabalha no Tribunal Regional do Trabalho da 14° Região, esta na areá de desenvolvimento de software a 7 anos tendo estudado e trabalhado com C#, ASP .NET, ASP.NET MVC, JAVA, JSF, play framework, PHP, HTML, CSS e javascript. Um entusiasta das tecnologias web acessíveis com usabilidade, responsividade e dinamismo."
    company: "Tribunal Regional do Trabalho da 14ª Regiao (TRT-RO)"
    presentation:
      title: "PlayFramework"
      time: "19h00"
  -
    name: "Andrei Daldegan"
    photo: "http://i.imgur.com/gXVp7tv.jpg"
    bio: "Conta com 15 anos de experiência no ramo de desenvolvimento de software, atuando principalmente no ramo de finanças e comércio exterior. Fundou a empresa de Desenvolvimento de Jogos Animvs Game Studio no ano de 2015, ano em que a mesma foi vencedora do 3º Concurso de Jogos do SEBRAE. Consta na sua carta de experiências: Unreal Engine, Unity 3D, Libgdx, C++, Java, C#, desenvolvimento Mobile nas plataformas Android e iOS, arquitetura de sofware, entre outras."
    company: "Animvs Game Studio (Curitiba-PR)"
    presentation:
      title: "Desenvolvimento de Games"
      time: "20h00"
  -
    name: "Intervalo"
    time: "21h00"
  -
    name: "Thiago Fleury"
    photo: "http://i.imgur.com/4BtiUL9.jpg"
    bio: "15 anos de experiência na área de infraestrutura atuando com tecnologias microsoft, websense, checkpoint, netbackup, fluke, entre outros."
    company: "Tribunal de Justiça - Área de Segurança da Informação. (TJ-RO)"
    presentation:
      title: "Estratégias de Backup"
      time: "22h00"
  -
    name: "Frederico Ferrão"
    photo: "http://i.imgur.com/oawHAHZ.jpg"
    bio: "Analista de Tecnologia da Informação no Tribunal Regional do Trabalho da 14ª Região, esta na área de desenvolvimento de software há 14 anos, tendo estudado e trabalhado com Delphi, Natural Adabas e Java, atualmente estuda programação funcional na linguagem Scala."
    company: "Tribunal Regional do Trabalho da 14ª Regiao (TRT-RO)"
    presentation:
      title: "Scala"
      time: "23h00"
  -
    name: "Rousseau Braga"
    photo: "http://i.imgur.com/u16NQSk.jpg"
    bio: "DevOps do TCE  e especialista com MBA em Engenharia de Software em Métodos Ágeis pela IGTI. Tem experiência de mais de 20 anos com informática, morou em Dublin/IR por um ano onde trabalhou com Python. Além disso vem  trabalhando com diversas tecnologias open source, pais de três filhos e nas horas vagas gosta de jogar Starcraft II, tocar guitarra e ficar falando sobre assuntos Tech com os amigos."
    company: "Tribunal de Contas do Estado (TCE-RO)"
    presentation:
      title: "SailsJS"
      time: "00h00"
  -
    name: "Networking"
    time: "01h00"
  -
    name: "Encerramento"
    time: "02h00"

# List of Sponsors
sponsors:
  -
    name: "Leite Fresquinho"
    logo: "https://pbs.twimg.com/profile_images/1126389999/logo_queijo_400x400.jpg"
    url: "https://www.facebook.com/LeiteFresquinho"

# List of Partners
partners:
  -
    name: "Redeconv"
    logo: "https://www.redeconv.com.br/assets/logo-66cfdb9c68958b9713c2e7474044fb33.png"
    url: "http://www.redeconv.com.br"
  -
    name: "Netpix Agência Web"
    logo: "http://netpix.com.br/content/data/uploads/2014/09/logo-netpix2.png"
    url: "http://www.netpix.com.br"
  -
    name: "Leite Fresquinho"
    logo: "https://pbs.twimg.com/profile_images/1126389999/logo_queijo_400x400.jpg"
    url: "https://www.facebook.com/LeiteFresquinho"
  -
    name: "BrazilJS"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"

# About section
about_section:
   title: "Sobre"
   description:
    -
      p: "O \"BEER && CODE\" é um evento idealizado em 2013 por Eduardo Mourão que teve como objetivo unir a classe tecnológica do Estado de Rondônia para troca de informações, ideias e apresentações das novas ferramentas e recursos de trabalho na área."
    -
      p: "A primeira edição em 2013 ocorreu na empresa Redeconv, em Porto Velho, da qual Eduardo era sócio e contou com a participação apenas de convidados e amigos da cidade para apresentações de projetos e as novidades do mercado."
    -
      p: "Após esse evento \"teste\" que contou com pelo menos 50 pessoas, ocorreu mais um encontro, agora em 2015, conhecido como \"meetup\" para discutirmos a segunda edição do \"BEER && CODE\", novamente com apresentações sobre desenvolvimento de sistemas e o uso delas no mercado de trabalho, já contando com mais de 100 pessoas após a divulgação um pouco mais ampla."
    -
      p: "Para essa edição a participação será limitada em 150 pessoas, com uma programação composta por palestras (7 no total) e discussões. Além, é claro, da cerveja que dá nome ao evento."

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
   c4p_url: "http://call4paperz.com"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.com"
   c4p_rules_caption: "Read the rules."

# Contact section
contact_section:
   title: "Contato"
   text: "Contact us if you have any questions."
   contacts:
   -
     title: "Email"
     link: "mailto:your_email@domain"
   -
     title: "Facebook"
     link: "https://www.facebook.com/yourpage"
   email: "your_email@domain"
   twitter_url: "http://twitter.com/your_twitter"
   twitter_username: "@your_twitter"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false

# Schedule section
schedule_section:
   title: "Programação"
   text: "A nata da programação de Rondônia em um só evento!"
   time: "Hora"
   slot: "Programação"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
